FROM node:20-alpine

WORKDIR /inspector

RUN npm install -g @modelcontextprotocol/inspector

EXPOSE 6274 6277

ENV HOST=0.0.0.0
ENV CLIENT_PORT=6274
ENV PORT=6277

CMD ["npx", "@modelcontextprotocol/inspector"]